version: '3.8'

services:
  db:
    image: mysql:8.0-bookworm
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE : ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile-spring
#    container_name: spring-app
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile-dev
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules

volumes:
  db_data: